name: Main

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn
      - run: yarn run validate
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
