name: NPM publish

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      - run: yarn
      - run: yarn run build
      - run: yarn config set '//registry.npmjs.org/:_authToken' "$NODE_AUTH_TOKEN"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - run: yarn publish --new-version $TAG
        env:
          TAG: ${{ steps.vars.outputs.tag }}
